import Head from "next/head";
import Image from "next/image";

const Card = ({ children, ...props }) => (
  <a
    sx={{
      margin: "1rem",
      padding: "1.5rem",
      textAlign: " left",
      color: "inherit",
      textDecoration: " none",
      border: "1px solid #eaeaea",
      borderRadius: " 10px",
      transition: "color 0.15s ease, border-color 0.15s ease",
      maxWidth: " 300px",
    }}
    {...props}
  >
    {children}
  </a>
);

export default function Home() {
  return (
    <div
      sx={{
        display: "flex",
        flexDirection: "column",
        minHeight: "100vh",
        justifyContent: "space-between",
      }}
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        sx={{
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "center",
          flex: "1",
        }}
      >
        <h1 sx={{ pb: 2, fontSize: 48, color: "neutral-300" }}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p sx={{ fontWeight: "bold" }}>
          Get started by editing{" "}
          <code
            sx={{
              borderRadius: 5,
              p: 1,
              bg: "base-300",
            }}
          >
            pages/index.js
          </code>{" "}
        </p>

        <span sx={{ p: 3 }} />

        <div
          sx={{
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            flexWrap: "wrap",
            maxWidth: "800px",
          }}
        >
          <Card href="https://nextjs.org/docs">
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </Card>

          <Card href="https://nextjs.org/learn">
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </Card>

          <Card href="https://github.com/vercel/next.js/tree/master/examples">
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </Card>

          <Card href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app">
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </Card>
        </div>
      </main>

      <footer
        sx={{
          py: "2rem",
          borderTop: "2px solid #eaeaea",
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
        }}
      >
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
