import Btn1 from "@cmp/Btn1";
import H1_ from "@cmp/H1";
import Header from "@cmp/Header";
// import {
//   useDownScrollEffect,
//   useScrollEffect,
//   useUpScrollEffect,
// } from "@useScrollEffect";
import Head from "next/head";
// import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header></Header>

      <H1_>
        {["it takes 7 seconds", "to make an impression", "we do it in 5"]}
      </H1_>

      <div
        sx={{
          marginTop: "-50vh",
          marginBottom: "30vh",
          "> *": { margin: "auto" },
        }}
      >
        <Btn1>{["PLAY", "FULL"]}</Btn1>
      </div>

      <p sx={{ textAlign: "center", width: "2rem", margin: "auto" }}>
        Occaecat est deserunt consectetur ipsum esse adipisicing excepteur.
        Laborum occaecat est do ad esse ipsum ullamco incididunt dolor quis
        dolore Lorem exercitation. Do ea officia cupidatat laboris esse
        consectetur magna ea labore. Ad id proident est dolore ipsum non aliqua.
        Velit occaecat ex consectetur cupidatat reprehenderit nulla in dolor
        amet fugiat ad sunt. Occaecat est deserunt consectetur ipsum esse
        adipisicing excepteur. Laborum occaecat est do ad esse ipsum ullamco
        incididunt dolor quis dolore Lorem exercitation. Do ea officia cupidatat
        laboris esse consectetur magna ea labore. Ad id proident est dolore
        ipsum non aliqua. Velit occaecat ex consectetur cupidatat reprehenderit
        nulla in dolor amet fugiat ad sunt. Occaecat est deserunt consectetur
        ipsum esse adipisicing excepteur. Laborum occaecat est do ad esse ipsum
        ullamco incididunt dolor quis dolore Lorem exercitation. Do ea officia
        cupidatat laboris esse consectetur magna ea labore. Ad id proident est
        dolore ipsum non aliqua. Velit occaecat ex consectetur cupidatat
        reprehenderit nulla in dolor amet fugiat ad sunt. Occaecat est deserunt
        consectetur ipsum esse adipisicing excepteur. Laborum occaecat est do ad
        esse ipsum ullamco incididunt dolor quis dolore Lorem exercitation. Do
        ea officia cupidatat laboris esse consectetur magna ea labore. Ad id
        proident est dolore ipsum non aliqua. Velit occaecat ex consectetur
        cupidatat reprehenderit nulla in dolor amet fugiat ad sunt. Occaecat est
        deserunt consectetur ipsum esse adipisicing excepteur. Laborum occaecat
        est do ad esse ipsum ullamco incididunt dolor quis dolore Lorem
        exercitation. Do ea officia cupidatat laboris esse consectetur magna ea
        labore. Ad id proident est dolore ipsum non aliqua. Velit occaecat ex
        consectetur cupidatat reprehenderit nulla in dolor amet fugiat ad sunt.
        Occaecat est deserunt consectetur ipsum esse adipisicing excepteur.
        Laborum occaecat est do ad esse ipsum ullamco incididunt dolor quis
        dolore Lorem exercitation. Do ea officia cupidatat laboris esse
        consectetur magna ea labore. Ad id proident est dolore ipsum non aliqua.
        Velit occaecat ex consectetur cupidatat reprehenderit nulla in dolor
        amet fugiat ad sunt. Occaecat est deserunt consectetur ipsum esse
        adipisicing excepteur. Laborum occaecat est do ad esse ipsum ullamco
        incididunt dolor quis dolore Lorem exercitation. Do ea officia cupidatat
        laboris esse consectetur magna ea labore. Ad id proident est dolore
        ipsum non aliqua. Velit occaecat ex consectetur cupidatat reprehenderit
        nulla in dolor amet fugiat ad sunt.
      </p>
    </>
  );
}
