import Btn1 from "@cmp/Btn1";
import H1_ from "@cmp/H1";
import Header from "@cmp/Header";
import LayerFixed from "@cmp/layers/LayerFixed";
import LayerRelative from "@cmp/layers/LayerRelative";
import LayerStick from "@cmp/layers/LayerStick";
import Section1 from "@cmp/Section1";
// import {
//   useDownScrollEffect,
//   useScrollEffect,
//   useUpScrollEffect,
// } from "@useScrollEffect";
import Head from "next/head";
// import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayerFixed zi={100}>
        <Header></Header>
      </LayerFixed>
      <div sx={{ minHeight: "100vh" }}> </div>
      <LayerStick
        zi={10}
        ss={{ minHeight: "100vh", placeContent: "center", display: "grid" }}
      >
        <H1_>
          {["it takes 7 seconds", "to make an impression", "we do it in 5"]}
        </H1_>
      </LayerStick>
      <LayerRelative
        zi={20}
        ss={{
          marginTop: "-50vh",
          marginBottom: "30vh",
          //    this margin will not work if the ` > *`
          // is inline element. is this case
          // the `Btn1` is `display:flex` so we are safe
          "> *": { margin: "auto" },
        }}
      >
        <Btn1>{["PLAY", "FULL"]}</Btn1>
      </LayerRelative>
      {/* //todo: I wanted to put this LayerRelative 
      inside of Section1 but there was a bug with the 
      video tag "uncomment the inside RealtiveLayer" */}
      <LayerRelative zi={30}>
        <Section1 />
      </LayerRelative>
      <LayerRelative zi={40} ss={{ bg: "base" }}>
        <p sx={{ textAlign: "center", width: "2rem", margin: "auto" }}>
          Occaecat est deserunt consectetur ipsum esse adipisicing excepteur.
          Laborum occaecat est do ad esse ipsum ullamco incididunt dolor quis
          dolore Lorem exercitation. Do ea officia cupidatat laboris esse
          consectetur magna ea labore. Ad id proident est dolore ipsum non
          aliqua. Velit occaecat ex consectetur cupidatat reprehenderit nulla in
          dolor amet fugiat ad sunt. Occaecat est deserunt consectetur ipsum
          esse adipisicing excepteur. Laborum occaecat est do ad esse ipsum
          ullamco incididunt dolor quis dolore Lorem exercitation. Do ea officia
          cupidatat laboris esse consectetur magna ea labore. Ad id proident est
          dolore ipsum non aliqua. Velit occaecat ex consectetur cupidatat
          reprehenderit nulla in dolor amet fugiat ad sunt. Occaecat est
          deserunt consectetur ipsum esse adipisicing excepteur. Laborum
          occaecat est do ad esse ipsum ullamco incididunt dolor quis dolore
          Lorem exercitation. Do ea officia cupidatat laboris esse consectetur
          magna ea labore. Ad id proident est dolore ipsum non aliqua. Velit
          occaecat ex consectetur cupidatat reprehenderit nulla in dolor amet
          fugiat ad sunt. Occaecat est deserunt consectetur ipsum esse
          adipisicing excepteur. Laborum occaecat est do ad esse ipsum ullamco
          incididunt dolor quis dolore Lorem exercitation. Do ea officia
          cupidatat laboris esse consectetur magna ea labore. Ad id proident est
          dolore ipsum non aliqua. Velit occaecat ex consectetur cupidatat
          reprehenderit nulla in dolor amet fugiat ad sunt. Occaecat est
          deserunt consectetur ipsum esse adipisicing excepteur. Laborum
          occaecat est do ad esse ipsum ullamco incididunt dolor quis dolore
          Lorem exercitation. Do ea officia cupidatat laboris esse consectetur
          magna ea labore. Ad id proident est dolore ipsum non aliqua. Velit
          occaecat ex consectetur cupidatat reprehenderit nulla in dolor amet
          fugiat ad sunt. Occaecat est deserunt consectetur ipsum esse
          adipisicing excepteur. Laborum occaecat est do ad esse ipsum ullamco
          incididunt dolor quis dolore Lorem exercitation. Do ea officia
          cupidatat laboris esse consectetur magna ea labore. Ad id proident est
          dolore ipsum non aliqua. Velit occaecat ex consectetur cupidatat
          reprehenderit nulla in dolor amet fugiat ad sunt. Occaecat est
          deserunt consectetur ipsum esse adipisicing excepteur. Laborum
          occaecat est do ad esse ipsum ullamco incididunt dolor quis dolore
          Lorem exercitation. Do ea officia cupidatat laboris esse consectetur
          magna ea labore. Ad id proident est dolore ipsum non aliqua. Velit
          occaecat ex consectetur cupidatat reprehenderit nulla in dolor amet
          fugiat ad sunt.
        </p>
      </LayerRelative>
    </>
  );
}
